version: '3.8'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py"]
    deploy:
      restart_policy:
        condition: on-failure

  parser:
    build:
      context: .
      dockerfile: parser/Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "parser/main.py"]
    deploy:
      restart_policy:
        condition: on-failure

  cron:
    build:
      context: .
      dockerfile: Dockerfile-cron
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      restart_policy:
        condition: on-failure


  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  postgres_data: